server:
  port: 9002
spring:
  application:
    name: tfjy-auth3-rbac-service
  zipkin:
    base-url: http://114.55.27.152:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 114.55.27.152:8848

  redis:
    host: d-redis.tfjybj.cn
    port: 6379

## Reids配置
# Redis服务器地址
# 单机版配置

# 集群版本配置 多个之间用，逗号隔开
## spring.redis.cluster.nodes=127.0.0.1:6379

# redis最大重连数
redis:
  cluster:
    max-redirects: 3
# Redis服务器连接密码（默认为空）
  password:
# 最大空闲数
  maxIdle: 5
# 连接池的最大数据库连接数。
  maxTotal: 5
# 最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
# 连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
# 每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 3
# 逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
# 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
# 在空闲时检查有效性, 默认false
  testWhileIdle: true

